version: '3.7'
services:
  mad_db_service:
    build: ./mad_db_service
    container_name: mad_db_service
    restart: on-failure
    env_file:
      - .env
    command: bash -c "make"
    volumes:
      - ./mad_db_service:/app
    ports:
      - 8084:8000


  mad_postgres_service:
    image: postgres:16
    container_name: mad_postgres_service
    env_file:
      - .env
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "effective_cache_size=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=512MB"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=30s"
    restart: unless-stopped
    ports:
      - 5433:5432


  mad_adminer:
    image: adminer
    container_name: mad_adminer_service
    restart: always
    ports:
      - 8083:8080


  mad_minio:
    image: minio/minio:latest
    hostname: "minio"
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: mad
      MINIO_ROOT_PASSWORD: madmadmad
    restart: always
    volumes:
      - minio-storage:/data


volumes:
  minio-storage:
